// Canonical metadata for the 114 surahs of the Quran.
// This is structural reference data (names, verse counts, revelation type) —
// not generated religious text. Source: standard Islamic reference tables.

export type RevelationType = 'meccan' | 'medinan';

export interface SurahMeta {
  id: number; // 1..114
  name: string; // Arabic name
  nameTranslation: string; // meaning
  nameEnglish: string; // transliteration
  verses: number; // ayah count
  revelation: RevelationType;
}

export const SURAHS: SurahMeta[] = [
  { id: 1, name: 'الفاتحة', nameTranslation: 'الفاتحة', nameEnglish: 'Al-Fatihah', verses: 7, revelation: 'meccan' },
  { id: 2, name: 'البقرة', nameTranslation: 'البقرة', nameEnglish: 'Al-Baqarah', verses: 286, revelation: 'medinan' },
  { id: 3, name: 'آل عمران', nameTranslation: 'آل عمران', nameEnglish: 'Aal-E-Imran', verses: 200, revelation: 'medinan' },
  { id: 4, name: 'النساء', nameTranslation: 'النساء', nameEnglish: 'An-Nisa', verses: 176, revelation: 'medinan' },
  { id: 5, name: 'المائدة', nameTranslation: 'المائدة', nameEnglish: 'Al-Maidah', verses: 120, revelation: 'medinan' },
  { id: 6, name: 'الأنعام', nameTranslation: 'الأنعام', nameEnglish: 'Al-Anam', verses: 165, revelation: 'meccan' },
  { id: 7, name: 'الأعراف', nameTranslation: 'الأعراف', nameEnglish: 'Al-Araf', verses: 206, revelation: 'meccan' },
  { id: 8, name: 'الأنفال', nameTranslation: 'الأنفال', nameEnglish: 'Al-Anfal', verses: 75, revelation: 'medinan' },
  { id: 9, name: 'التوبة', nameTranslation: 'التوبة', nameEnglish: 'At-Tawbah', verses: 129, revelation: 'medinan' },
  { id: 10, name: 'يونس', nameTranslation: 'يونس', nameEnglish: 'Yunus', verses: 109, revelation: 'meccan' },
  { id: 11, name: 'هود', nameTranslation: 'هود', nameEnglish: 'Hud', verses: 123, revelation: 'meccan' },
  { id: 12, name: 'يوسف', nameTranslation: 'يوسف', nameEnglish: 'Yusuf', verses: 111, revelation: 'meccan' },
  { id: 13, name: 'الرعد', nameTranslation: 'الرعد', nameEnglish: 'Ar-Rad', verses: 43, revelation: 'medinan' },
  { id: 14, name: 'إبراهيم', nameTranslation: 'إبراهيم', nameEnglish: 'Ibrahim', verses: 52, revelation: 'meccan' },
  { id: 15, name: 'الحجر', nameTranslation: 'الحجر', nameEnglish: 'Al-Hijr', verses: 99, revelation: 'meccan' },
  { id: 16, name: 'النحل', nameTranslation: 'النحل', nameEnglish: 'An-Nahl', verses: 128, revelation: 'meccan' },
  { id: 17, name: 'الإسراء', nameTranslation: 'الإسراء', nameEnglish: 'Al-Isra', verses: 111, revelation: 'meccan' },
  { id: 18, name: 'الكهف', nameTranslation: 'الكهف', nameEnglish: 'Al-Kahf', verses: 110, revelation: 'meccan' },
  { id: 19, name: 'مريم', nameTranslation: 'مريم', nameEnglish: 'Maryam', verses: 98, revelation: 'meccan' },
  { id: 20, name: 'طه', nameTranslation: 'طه', nameEnglish: 'Ta-Ha', verses: 135, revelation: 'meccan' },
  { id: 21, name: 'الأنبياء', nameTranslation: 'الأنبياء', nameEnglish: 'Al-Anbiya', verses: 112, revelation: 'meccan' },
  { id: 22, name: 'الحج', nameTranslation: 'الحج', nameEnglish: 'Al-Hajj', verses: 78, revelation: 'medinan' },
  { id: 23, name: 'المؤمنون', nameTranslation: 'المؤمنون', nameEnglish: 'Al-Muminun', verses: 118, revelation: 'meccan' },
  { id: 24, name: 'النور', nameTranslation: 'النور', nameEnglish: 'An-Nur', verses: 64, revelation: 'medinan' },
  { id: 25, name: 'الفرقان', nameTranslation: 'الفرقان', nameEnglish: 'Al-Furqan', verses: 77, revelation: 'meccan' },
  { id: 26, name: 'الشعراء', nameTranslation: 'الشعراء', nameEnglish: 'Ash-Shuara', verses: 227, revelation: 'meccan' },
  { id: 27, name: 'النمل', nameTranslation: 'النمل', nameEnglish: 'An-Naml', verses: 93, revelation: 'meccan' },
  { id: 28, name: 'القصص', nameTranslation: 'القصص', nameEnglish: 'Al-Qasas', verses: 88, revelation: 'meccan' },
  { id: 29, name: 'العنكبوت', nameTranslation: 'العنكبوت', nameEnglish: 'Al-Ankabut', verses: 69, revelation: 'meccan' },
  { id: 30, name: 'الروم', nameTranslation: 'الروم', nameEnglish: 'Ar-Rum', verses: 60, revelation: 'meccan' },
  { id: 31, name: 'لقمان', nameTranslation: 'لقمان', nameEnglish: 'Luqman', verses: 34, revelation: 'meccan' },
  { id: 32, name: 'السجدة', nameTranslation: 'السجدة', nameEnglish: 'As-Sajdah', verses: 30, revelation: 'meccan' },
  { id: 33, name: 'الأحزاب', nameTranslation: 'الأحزاب', nameEnglish: 'Al-Ahzab', verses: 73, revelation: 'medinan' },
  { id: 34, name: 'سبأ', nameTranslation: 'سبأ', nameEnglish: 'Saba', verses: 54, revelation: 'meccan' },
  { id: 35, name: 'فاطر', nameTranslation: 'فاطر', nameEnglish: 'Fatir', verses: 45, revelation: 'meccan' },
  { id: 36, name: 'يس', nameTranslation: 'يس', nameEnglish: 'Ya-Sin', verses: 83, revelation: 'meccan' },
  { id: 37, name: 'الصافات', nameTranslation: 'الصافات', nameEnglish: 'As-Saffat', verses: 182, revelation: 'meccan' },
  { id: 38, name: 'ص', nameTranslation: 'ص', nameEnglish: 'Sad', verses: 88, revelation: 'meccan' },
  { id: 39, name: 'الزمر', nameTranslation: 'الزمر', nameEnglish: 'Az-Zumar', verses: 75, revelation: 'meccan' },
  { id: 40, name: 'غافر', nameTranslation: 'غافر', nameEnglish: 'Ghafir', verses: 85, revelation: 'meccan' },
  { id: 41, name: 'فصلت', nameTranslation: 'فصلت', nameEnglish: 'Fussilat', verses: 54, revelation: 'meccan' },
  { id: 42, name: 'الشورى', nameTranslation: 'الشورى', nameEnglish: 'Ash-Shura', verses: 53, revelation: 'meccan' },
  { id: 43, name: 'الزخرف', nameTranslation: 'الزخرف', nameEnglish: 'Az-Zukhruf', verses: 89, revelation: 'meccan' },
  { id: 44, name: 'الدخان', nameTranslation: 'الدخان', nameEnglish: 'Ad-Dukhan', verses: 59, revelation: 'meccan' },
  { id: 45, name: 'الجاثية', nameTranslation: 'الجاثية', nameEnglish: 'Al-Jathiyah', verses: 37, revelation: 'meccan' },
  { id: 46, name: 'الأحقاف', nameTranslation: 'الأحقاف', nameEnglish: 'Al-Ahqaf', verses: 35, revelation: 'meccan' },
  { id: 47, name: 'محمد', nameTranslation: 'محمد', nameEnglish: 'Muhammad', verses: 38, revelation: 'medinan' },
  { id: 48, name: 'الفتح', nameTranslation: 'الفتح', nameEnglish: 'Al-Fath', verses: 29, revelation: 'medinan' },
  { id: 49, name: 'الحجرات', nameTranslation: 'الحجرات', nameEnglish: 'Al-Hujurat', verses: 18, revelation: 'medinan' },
  { id: 50, name: 'ق', nameTranslation: 'ق', nameEnglish: 'Qaf', verses: 45, revelation: 'meccan' },
  { id: 51, name: 'الذاريات', nameTranslation: 'الذاريات', nameEnglish: 'Adh-Dhariyat', verses: 60, revelation: 'meccan' },
  { id: 52, name: 'الطور', nameTranslation: 'الطور', nameEnglish: 'At-Tur', verses: 49, revelation: 'meccan' },
  { id: 53, name: 'النجم', nameTranslation: 'النجم', nameEnglish: 'An-Najm', verses: 62, revelation: 'meccan' },
  { id: 54, name: 'القمر', nameTranslation: 'القمر', nameEnglish: 'Al-Qamar', verses: 55, revelation: 'meccan' },
  { id: 55, name: 'الرحمن', nameTranslation: 'الرحمن', nameEnglish: 'Ar-Rahman', verses: 78, revelation: 'medinan' },
  { id: 56, name: 'الواقعة', nameTranslation: 'الواقعة', nameEnglish: 'Al-Waqiah', verses: 96, revelation: 'meccan' },
  { id: 57, name: 'الحديد', nameTranslation: 'الحديد', nameEnglish: 'Al-Hadid', verses: 29, revelation: 'medinan' },
  { id: 58, name: 'المجادلة', nameTranslation: 'المجادلة', nameEnglish: 'Al-Mujadila', verses: 22, revelation: 'medinan' },
  { id: 59, name: 'الحشر', nameTranslation: 'الحشر', nameEnglish: 'Al-Hashr', verses: 24, revelation: 'medinan' },
  { id: 60, name: 'الممتحنة', nameTranslation: 'الممتحنة', nameEnglish: 'Al-Mumtahanah', verses: 13, revelation: 'medinan' },
  { id: 61, name: 'الصف', nameTranslation: 'الصف', nameEnglish: 'As-Saff', verses: 14, revelation: 'medinan' },
  { id: 62, name: 'الجمعة', nameTranslation: 'الجمعة', nameEnglish: 'Al-Jumuah', verses: 11, revelation: 'medinan' },
  { id: 63, name: 'المنافقون', nameTranslation: 'المنافقون', nameEnglish: 'Al-Munafiqun', verses: 11, revelation: 'medinan' },
  { id: 64, name: 'التغابن', nameTranslation: 'التغابن', nameEnglish: 'At-Taghabun', verses: 18, revelation: 'medinan' },
  { id: 65, name: 'الطلاق', nameTranslation: 'الطلاق', nameEnglish: 'At-Talaq', verses: 12, revelation: 'medinan' },
  { id: 66, name: 'التحريم', nameTranslation: 'التحريم', nameEnglish: 'At-Tahrim', verses: 12, revelation: 'medinan' },
  { id: 67, name: 'الملك', nameTranslation: 'الملك', nameEnglish: 'Al-Mulk', verses: 30, revelation: 'meccan' },
  { id: 68, name: 'القلم', nameTranslation: 'القلم', nameEnglish: 'Al-Qalam', verses: 52, revelation: 'meccan' },
  { id: 69, name: 'الحاقة', nameTranslation: 'الحاقة', nameEnglish: 'Al-Haqqah', verses: 52, revelation: 'meccan' },
  { id: 70, name: 'المعارج', nameTranslation: 'المعارج', nameEnglish: 'Al-Maarij', verses: 44, revelation: 'meccan' },
  { id: 71, name: 'نوح', nameTranslation: 'نوح', nameEnglish: 'Nooh', verses: 28, revelation: 'meccan' },
  { id: 72, name: 'الجن', nameTranslation: 'الجن', nameEnglish: 'Al-Jinn', verses: 28, revelation: 'meccan' },
  { id: 73, name: 'المزمل', nameTranslation: 'المزمل', nameEnglish: 'Al-Muzzammil', verses: 20, revelation: 'meccan' },
  { id: 74, name: 'المدثر', nameTranslation: 'المدثر', nameEnglish: 'Al-Muddaththir', verses: 56, revelation: 'meccan' },
  { id: 75, name: 'القيامة', nameTranslation: 'القيامة', nameEnglish: 'Al-Qiyamah', verses: 40, revelation: 'meccan' },
  { id: 76, name: 'الإنسان', nameTranslation: 'الإنسان', nameEnglish: 'Al-Insan', verses: 31, revelation: 'medinan' },
  { id: 77, name: 'المرسلات', nameTranslation: 'المرسلات', nameEnglish: 'Al-Mursalat', verses: 50, revelation: 'meccan' },
  { id: 78, name: 'النبأ', nameTranslation: 'النبأ', nameEnglish: 'An-Naba', verses: 40, revelation: 'meccan' },
  { id: 79, name: 'النازعات', nameTranslation: 'النازعات', nameEnglish: 'An-Naziat', verses: 46, revelation: 'meccan' },
  { id: 80, name: 'عبس', nameTranslation: 'عبس', nameEnglish: 'Abasa', verses: 42, revelation: 'meccan' },
  { id: 81, name: 'التكوير', nameTranslation: 'التكوير', nameEnglish: 'At-Takwir', verses: 29, revelation: 'meccan' },
  { id: 82, name: 'الانفطار', nameTranslation: 'الانفطار', nameEnglish: 'Al-Infitar', verses: 19, revelation: 'meccan' },
  { id: 83, name: 'المطففين', nameTranslation: 'المطففين', nameEnglish: 'Al-Mutaffifin', verses: 36, revelation: 'meccan' },
  { id: 84, name: 'الانشقاق', nameTranslation: 'الانشقاق', nameEnglish: 'Al-Inshiqaq', verses: 25, revelation: 'meccan' },
  { id: 85, name: 'البروج', nameTranslation: 'البروج', nameEnglish: 'Al-Buruj', verses: 22, revelation: 'meccan' },
  { id: 86, name: 'الطارق', nameTranslation: 'الطارق', nameEnglish: 'At-Tariq', verses: 17, revelation: 'meccan' },
  { id: 87, name: 'الأعلى', nameTranslation: 'الأعلى', nameEnglish: 'Al-Ala', verses: 19, revelation: 'meccan' },
  { id: 88, name: 'الغاشية', nameTranslation: 'الغاشية', nameEnglish: 'Al-Ghashiyah', verses: 26, revelation: 'meccan' },
  { id: 89, name: 'الفجر', nameTranslation: 'الفجر', nameEnglish: 'Al-Fajr', verses: 30, revelation: 'meccan' },
  { id: 90, name: 'البلد', nameTranslation: 'البلد', nameEnglish: 'Al-Balad', verses: 20, revelation: 'meccan' },
  { id: 91, name: 'الشمس', nameTranslation: 'الشمس', nameEnglish: 'Ash-Shams', verses: 15, revelation: 'meccan' },
  { id: 92, name: 'الليل', nameTranslation: 'الليل', nameEnglish: 'Al-Lail', verses: 21, revelation: 'meccan' },
  { id: 93, name: 'الضحى', nameTranslation: 'الضحى', nameEnglish: 'Ad-Duha', verses: 11, revelation: 'meccan' },
  { id: 94, name: 'الشرح', nameTranslation: 'الشرح', nameEnglish: 'Ash-Sharh', verses: 8, revelation: 'meccan' },
  { id: 95, name: 'التين', nameTranslation: 'التين', nameEnglish: 'At-Tin', verses: 8, revelation: 'meccan' },
  { id: 96, name: 'العلق', nameTranslation: 'العلق', nameEnglish: 'Al-Alaq', verses: 19, revelation: 'meccan' },
  { id: 97, name: 'القدر', nameTranslation: 'القدر', nameEnglish: 'Al-Qadr', verses: 5, revelation: 'meccan' },
  { id: 98, name: 'البينة', nameTranslation: 'البينة', nameEnglish: 'Al-Bayyinah', verses: 8, revelation: 'medinan' },
  { id: 99, name: 'الزلزلة', nameTranslation: 'الزلزلة', nameEnglish: 'Az-Zalzalah', verses: 8, revelation: 'medinan' },
  { id: 100, name: 'العاديات', nameTranslation: 'العاديات', nameEnglish: 'Al-Adiyat', verses: 11, revelation: 'meccan' },
  { id: 101, name: 'القارعة', nameTranslation: 'القارعة', nameEnglish: 'Al-Qariah', verses: 11, revelation: 'meccan' },
  { id: 102, name: 'التكاثر', nameTranslation: 'التكاثر', nameEnglish: 'At-Takathur', verses: 8, revelation: 'meccan' },
  { id: 103, name: 'العصر', nameTranslation: 'العصر', nameEnglish: 'Al-Asr', verses: 3, revelation: 'meccan' },
  { id: 104, name: 'الهمزة', nameTranslation: 'الهمزة', nameEnglish: 'Al-Humazah', verses: 9, revelation: 'meccan' },
  { id: 105, name: 'الفيل', nameTranslation: 'الفيل', nameEnglish: 'Al-Fil', verses: 5, revelation: 'meccan' },
  { id: 106, name: 'قريش', nameTranslation: 'قريش', nameEnglish: 'Quraish', verses: 4, revelation: 'meccan' },
  { id: 107, name: 'الماعون', nameTranslation: 'الماعون', nameEnglish: 'Al-Maun', verses: 7, revelation: 'meccan' },
  { id: 108, name: 'الكوثر', nameTranslation: 'الكوثر', nameEnglish: 'Al-Kawthar', verses: 3, revelation: 'meccan' },
  { id: 109, name: 'الكافرون', nameTranslation: 'الكافرون', nameEnglish: 'Al-Kafirun', verses: 6, revelation: 'meccan' },
  { id: 110, name: 'النصر', nameTranslation: 'النصر', nameEnglish: 'An-Nasr', verses: 3, revelation: 'medinan' },
  { id: 111, name: 'المسد', nameTranslation: 'المسد', nameEnglish: 'Al-Masad', verses: 5, revelation: 'meccan' },
  { id: 112, name: 'الإخلاص', nameTranslation: 'الإخلاص', nameEnglish: 'Al-Ikhlas', verses: 4, revelation: 'meccan' },
  { id: 113, name: 'الفلق', nameTranslation: 'الفلق', nameEnglish: 'Al-Falaq', verses: 5, revelation: 'meccan' },
  { id: 114, name: 'الناس', nameTranslation: 'الناس', nameEnglish: 'An-Nas', verses: 6, revelation: 'meccan' },
];

export function getSurah(id: number): SurahMeta | undefined {
  return SURAHS.find((s) => s.id === id);
}

export const TOTAL_VERSES = SURAHS.reduce((sum, s) => sum + s.verses, 0); // 6236
